name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  use-github-app-token:
    uses: eamonnk418/github-app-token/.github/workflows/create-github-app-token.yml@v1

  build:
    runs-on: ubuntu-latest
    needs: use-github-app-token
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".tool-versions"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
